### PR TITLE
use Fuzzy ident lookup, which fixes tooltip absence for operators

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
image

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Can you run `build.cmd test` and commit changes in test results?

**Comment by vasily-kirichenko** [comment]
```
1) Failed : FsAutoComplete.Tests.normalCracking
  Expected and actual are both <Microsoft.FSharp.Collections.FSharpList`1[System.String]>
at FsAutoComplete.Tests.normalCracking() in D:\github\FsAutoComplete\test\FsAutoComplete.Tests\Tests.fs:line 38

2) Failed : FsAutoComplete.Tests.normalCracking
  Expected and actual are both <Microsoft.FSharp.Collections.FSharpList`1[System.String]>
at FsAutoComplete.Tests.normalCracking() in D:\github\FsAutoComplete\test\FsAutoComplete.Tests\Tests.fs:line 38
```
Great diagnosability :)

**Comment by Krzysztof-Cieslak** [comment]
Nvm, this looks good enough for me.

**Comment by Krzysztof-Cieslak** [comment]
I'll try to fix tests later

**Pull request merged**
