### PR TITLE
new fsproj

### PR DESCRIPTION
**Pull request by enricosada**
- project.json => read fsc args from `dotnet-compile-fsc.rsp` response file
- new fsproj => use `Dotnet.ProjInfo` to read fsc args

TODO

- [x] fsc args to initialize FSC
- [x] p2p ref
- [x] doesnt require `dotnet build`
- [ ] doesnt require `dotnet restore`

Use this my FSAC fork (from `learn_new_fsproj` in https://github.com/enricosada/FsAutoComplete/tree/learn_new_fsproj ). 

how to use vscode and dev FSAC in Visual Studio, see https://github.com/ionide/ionide-vscode-fsharp/blob/master/DEVGUIDE.md#working-with-fsac

You can use samples: https://github.com/enricosada/DotnetNewFsprojTestingSamples ready to use

just:

- `cd sample1`
- `dotnet restore c1`

before opening in vscode (it should continue fail already if not restored, but didnt test it if work after restore)

that `sample1` is configured to `F5`, so will build and debug.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Awesome work, @enricosada! :clap: :clap:

I gave it a try following the instructions an it's working for me :+1: I just got a problem with the F# colorizer, but I guess this is something related with the VSCode dev instance. All the Ionide features were working: code lenses, tooltips, intellisense, finding all references, peeking definition, renaming...

Tested on Windows 10 with latest dotnet SDK

**Comment by enricosada** [comment]
@Krzysztof-Cieslak **do not** release an ionide version with this please, i need to publish packages on nuget.org.
this will break current workaround for intellisense

**Comment by enricosada** [comment]
Also, need to test it on osx/unix, i think. i can do osx this weekend probably

**Comment by Krzysztof-Cieslak** [comment]
Woops, if that's the case, I'll revert the merge for now...

**Comment by Krzysztof-Cieslak** [comment]
I guess you'll need to submit PR again, sorry.

**Comment by enricosada** [comment]
@Krzysztof-Cieslak np, my bad, i was saying to much "it works" 😄

**Comment by alfonsogarciacaro** [comment]
I will test in OSX later later in the afternoon and confirm with you :+1:

**Comment by baronfel** [comment]
I'm running on OSX Sierra with dotnet version 1.0.1 and can't restore given the setup above:

```
 17-03-16/12:10 ~/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1   master  dotnet restore
  Restoring packages for /Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/l1/l1.fsproj...
  Restoring packages for /Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1/c1.fsproj...
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1/c1.fsproj]
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   The type initializer for 'System.Net.Http.CurlHandler' threw an exception. [/Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1/c1.fsproj]
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   The type initializer for 'Http' threw an exception. [/Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1/c1.fsproj]
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   The type initializer for 'HttpInitializer' threw an exception. [/Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1/c1.fsproj]
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   The type initializer for 'CryptoInitializer' threw an exception. [/Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1/c1.fsproj]
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error :   Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found. [/Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1/c1.fsproj]
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error :    (Exception from HRESULT: 0x8007007E) [/Users/chet/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1/c1.fsproj]
 17-03-16/12:10 ~/code/OSS/DotnetNewFsprojTestingSamples/sample1/c1   master  dotnet --version
1.0.1
```

I've ensured that openssl is installed, and dotnet restore of a branch new C# project created using `dotnet new` works just fine.  How can I help debug?

**Comment by enricosada** [comment]
@baronfel probably the c# use the local packages embeeded with dotnet core, and doesnt go to nuget.org (that's the issue afaik). If you add another package (like newtonsoft.json or one not in your local cache) should fail c# too.
If does, i think you should open a bug in `dotnet/core` repo about that.

**Comment by baronfel** [comment]
Perfect use case, that failed for me locally. I'll write up an issue.

**Comment by baronfel** [comment]
Submitted under dotnet/core#560

**Comment by alfonsogarciacaro** [comment]
Ok, this is weird. For me in macOS Sierra 10.12.3 Newtonsoft.Json installs without problems.

```shell
~/d/D/s/l1 ❯❯❯ dotnet add package Newtonsoft.Json
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing /var/folders/f7/43t6bltj7cv31lszylz470t80000gn/T/tmp8A70qW.tmp
info : Adding PackageReference for package 'Newtonsoft.Json' into project '/Users/alfonsogarciacaronunez/dev/DotnetNewFsprojTestingSamples/sample1/l1/l1.fsproj
'.
log  : Restoring packages for /Users/alfonsogarciacaronunez/dev/DotnetNewFsprojTestingSamples/sample1/l1/l1.fsproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/fsharp.net.sdk/index.json
info :   CACHE https://www.myget.org/F/netcorecli-fsc-1_0_0-intellisense/api/v3/flatcontainer/fsharp.net.sdk/index.json
info :   CACHE https://www.myget.org/F/netcorecli-fsc-1_0_0-intellisense/api/v3/flatcontainer/fsharp.net.sdk/1.0.2-rc2-006/fsharp.net.sdk.1.0.2-rc2-006.nupkg
info :   CACHE https://api.nuget.org/v3-flatcontainer/fsharp.core/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/fsharp.core/4.1.0.2/fsharp.core.4.1.0.2.nupkg
info :   GET https://www.myget.org/F/netcorecli-fsc-1_0_0-intellisense/api/v3/flatcontainer/fsharp.core/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/9.0.1/newtonsoft.json.9.0.1.nupkg
info :   GET https://www.myget.org/F/netcorecli-fsc-1_0_0-intellisense/api/v3/flatcontainer/newtonsoft.json/index.json
info :   NotFound https://www.myget.org/F/netcorecli-fsc-1_0_0-intellisense/api/v3/flatcontainer/fsharp.core/index.json 948ms
info :   NotFound https://www.myget.org/F/netcorecli-fsc-1_0_0-intellisense/api/v3/flatcontainer/newtonsoft.json/index.json 1023ms
info : Package 'Newtonsoft.Json' is compatible with all the specified frameworks in project '/Users/alfonsogarciacaronunez/dev/DotnetNewFsprojTestingSamples/sa
mple1/l1/l1.fsproj'.
info : PackageReference for package 'Newtonsoft.Json' version '9.0.1' updated in file '/Users/alfonsogarciacaronunez/dev/DotnetNewFsprojTestingSamples/sample1/
l1/l1.fsproj'.
```

However then Ionide intellisense tells me it cannot find the reference :/

screen shot 2017-03-16 at 23 23 20

**Comment by enricosada** [comment]
Follow up PR -> https://github.com/ionide/FsAutoComplete/pull/55

**Pull request merged**
