### PR TITLE
Add Background compilation

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
@vasily-kirichenko, @7sharp9

Still having some problems with communication through sockets with plugin side, but for testing purposes I'm displaying stuff in stdio. Seems to work

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Let me summarize:
* Any file saved in Code.
* Code sends "parseProjects" to FSAC.
* FSAC calls `FSharpChecker.CheckProjectInBackground` for all knows project (basically, for all projects it has found in active directory). This call is non blocking and returns immediately.
* FSAC subscribes for `FSharpChecker.FileChecked` event, which is raises by FCS when a file in any project has been checked in background (only in background? Does `FSharpChecker.ParseAndCheckFileInProject` raise it, too? If it's the case, will "parse" (checking dirty buffer) be damaged in any way (on Code side)?)
* On each above event FSAC gets check result via `FSharpChecker.GetBackgroundCheckResultsForFileInProject` and sends results to a WebSocket.
* (Code side is not pushed yet to review).
Looks good for me :)

@7sharp9 what do you think?

**Comment by 7sharp9** [comment]
`FileChecked` and `dirtynotify` work together, `FileChecked` tells the the file for which type checking is now available, `dirtyNotify` tells you which files now have potentially invalid check results because of this.  

A full check at the start then incremental file updates is normally the best way to use FCS.  And try to use CheckProject as little as possible and only when really needed like refactoring where you need all type checking up to date.

**Comment by vasily-kirichenko** [comment]
So it changes the way "parseProjects" works? I think we should implement https://github.com/ionide/ionide-vscode-fsharp/issues/255#issuecomment-257011043 'coz without it Linter and errors wont properly work.

After changing and saving a file the tail of the log looks like:
```
[10:18:56 INFO ] REQ (046) -> {parseProjects}
[10:18:56 DEBUG] RES (046) <- {parseProjects} in 7 ms: Kind={"errors"}
Data=[]
```

**Comment by Krzysztof-Cieslak** [comment]
Planning to merge it at last. Still not supporting Linter and other things mentioned by https://github.com/ionide/ionide-vscode-fsharp/issues/255#issuecomment-257011043 but it's good start. We can add other features to push notifications later, in separate PRs

Essentially workflow is as follow:
1. On any F# file save Code sends `parseProjects`
2. It starts background checking and returns (empty array, it's not really important)
3. On `FileChecked` errors are sent to Code through socket connection
4. Code subscribes to socket and display errors in error panel (this is not done for active editor - active editor is still handled by normal `parse` requests [ which returns errors for it even if file is not saved])

**Pull request merged**
