### PR TITLE
fixed: Suave dies if handlers raise exceptions

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
It seems to really fix tooltips disappearing: have not seen it even on FCS's `TypeChecker.fs` 15K file.

**Comment by forki** [comment]
:kiss:

**Comment by alfonsogarciacaro** [comment]
If this avoids the need of reloading VS Code window from time to time it will really make my day :clap:

**Comment by vasily-kirichenko** [comment]
@alfonsogarciacaro If this happens again, please create an issue with log output.

**Comment by alfonsogarciacaro** [comment]
I'll do! Sometimes I'm a bit lazy to report issues and just reload the window to continue my workflow, sorry! Thanks a lot for your hard work, @vasily-kirichenko!

**Comment by alfonsogarciacaro** [comment]
Ionide-fsharp responsiveness seems to have improved a lot with 2.8.2, thanks a lot! However, after programming for a while I still got this (I'm on Mac with latest VSCode):

```
threadService.ts:222 [Extension Host] [IONIDE-FSAC] RES (6111) <- {symboluse} ERROR in 26225 ms: Error: connect ETIMEDOUT 127.0.0.1:8429 Data=%O
threadService.ts:222 [Extension Host] [IONIDE-FSAC] RES (6112) <- {tooltip} ERROR in 26282 ms: Error: connect ETIMEDOUT 127.0.0.1:8429 Data=%O
threadService.ts:222 [Extension Host] rejected promise not handled within 1 second
shell.ts:441 connect ETIMEDOUT 127.0.0.1:8429: Error: connect ETIMEDOUT 127.0.0.1:8429
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)e.onUnexpectedError @ shell.ts:441(anonymous function) @ shell.ts:354e.onUnexpectedError @ errors.ts:68o @ errors.ts:83t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

This repeats forever. I cannot report issues to this fork, should I add it ionide-vscode-fsharp?

**Pull request merged**
